Fix/341/startup (#342)
* #341

* oops, logic backwards

---------

Co-authored-by: tevpg <tevpgx@gmail.com>

diff --git a/startup b/startup
--- a/startup
+++ b/startup
@@ -12,6 +12,16 @@ this_dir="$(pwd)"
 this_prog=$0
 prog_name="${0##*/}"
 
+pgrep -f 'python3 tagtracker.py' > /dev/null
+if [[ $? -eq 0 ]] ; then
+  echo TagTracker is already running!
+  echo
+  echo 'Look for another TagTracker running (e.g. in taskbar at bottom of screen).'
+  echo 'If all else fails, restart the computer.'
+  echo
+  exit 1
+fi
+
 echo "Starting TagTracker..."
 echo
 
