#341

diff --git a/startup b/startup
--- a/startup
+++ b/startup
@@ -12,6 +12,15 @@ this_dir="$(pwd)"
 this_prog=$0
 prog_name="${0##*/}"
 
+pgrep -f 'python3 tagtracker.py' > /dev/null
+if [[ $? -ne 0 ]] ; then
+  echo TagTracker is already running!
+  echo
+  echo 'Look for another TagTracker running (e.g. in taskbar at bottom of screen).'
+  echo 'If all else fails, restart the computer.'
+  echo
+fi
+
 echo "Starting TagTracker..."
 echo
 
