code formatting

diff --git a/tagtracker b/tagtracker
--- a/tagtracker
+++ b/tagtracker
@@ -8,19 +8,18 @@
 
 TT_DIR="$HOME/TagTracker"
 
-
 this_dir="$(pwd)"
 this_prog=$0
 prog_name="${0##*/}"
 
-pgrep -f 'python3[0-9\.]*\s+tagtracker.py' > /dev/null
-if [[ $? -eq 0 ]] ; then
-  echo TagTracker is already running!
-  echo
-  echo 'Look for another TagTracker running (e.g. in taskbar at bottom of screen).'
-  echo 'If all else fails, restart the computer.'
-  echo
-  exit 1
+pgrep -f 'python3[0-9\.]*\s+tagtracker.py' >/dev/null
+if [[ $? -eq 0 ]]; then
+    echo TagTracker is already running!
+    echo
+    echo 'Look for another TagTracker running (e.g. in taskbar at bottom of screen).'
+    echo 'If all else fails, restart the computer.'
+    echo
+    exit 1
 fi
 
 echo "Starting TagTracker..."
@@ -34,7 +33,7 @@ echo
 read -rp "Restart TagTracker? (Y/N): " confirm
 echo
 if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]; then
-  exec "$this_prog"
+    exec "$this_prog"
 fi
 # Do not restart
 cd "$this_dir" || exit 1
